config/routes.rb
Rails.application.routes.draw do
  
  resources :sales
  resources :categories
  resources :products
  devise_for :users
  
  get 'welcome/index'

  root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/product.rb
class Product < ActiveRecord::Base

	has_attached_file :cover, styles: {medium: "1200x720", thumb: "800x600" , mini: "400x300"}
	validates_attachment_content_type :cover , content_type: /\Aimage\/.*\Z/
   
    has_many :has_categories
	has_many :categories , through: :has_categories

	has_many :requests
	has_many :sales , through: :requests 
	
	after_create :save_categories
	after_update :update_categories

	def categories=(value)
     	@categories = value	
	end

	private

	def save_categories
		@categories.each do |category_id|
			HasCategory.create(category_id: category_id, product_id: self.id )
		end
	end

	def update_categories
		
		HasCategory.destroy_all(product_id: self.id )
		       
        @categories.each do |category_id|
			HasCategory.create(category_id: category_id, product_id: self.id )
		end 
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @q = params[:q]
    if @q
    @products = Product.where("nombre LIKE ? OR tamaño LIKE ?","%#{@q}%","%#{@q}%")
  else
    @products = Product.all
   end
    
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @categories = Category.all
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.categories = params[:categories]
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      @product.categories = params[:categories]
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:nombre, :descripcion, :pre_venta, :pre_comra, :tamaño, :marca, :stock, :stock_min, :cover,:categories)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
  <%= form_for(@product) do |f| %>
     <% if @product.errors.any? %>
        <div id="error_explanation col s12">
          <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
          <ul>
          <% @product.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="input-field col s12">
        <%= f.label :nombre %><br>
        <%= f.text_field :nombre %>
      </div>
      <div class="input-field col s12">
        <%= f.label :descripcion %><br>
        <%= f.text_area :descripcion, class: "materialize-textarea" %>
      </div>
      <div class="input-field col s12">
        <%= f.label :pre_venta %><br>
        <%= f.text_field :pre_venta %>
      </div>
      <div class="input-field col s12">
        <%= f.label :pre_comra %><br>
        <%= f.text_field :pre_comra %>
      </div>
      <div class="input-field col s12">
        <%= f.label :tamaño %><br>
        <%= f.text_field :tamaño %>
      </div>
      <div class="input-field col s12">
        <%= f.label :marca %><br>
        <%= f.text_field :marca %>
      </div>
      <div class="input-field col s12">
        <%= f.label :stock %><br>
        <%= f.number_field :stock %>
      </div>
      <div class="input-field col s12">
        <%= f.label :stock_min %><br>
        <%= f.number_field :stock_min %>
      </div>
      
      <div class="file-field input-field col s12">
        <div class="btn">
          <span>Imagen</span> 
          <%= f.file_field :cover%>
        </div>  
        <div class="file-path-wrapper">
           <input class="file-path validate" type="text">
        </div> 
      </div>
       
      <div class="input-field margtop col s12">
        <%= f.label :Categories %><br>
        <% @categories.each do |category| %>
         <div class="input-field col s12">
           <%= check_box_tag 'categories[]', category.id , false, :id => category.id, class: "filled-in" %>  
           <%= label_tag category.id, category.nombre %><br>      
        </div>
        <% end %> 
        <br>
    </div> 
    <div class="col s12">
         <%= link_to 'Nueva Categoria', new_category_path %>
       </div> 
       
      <div >
        <%= f.submit "Guardar" , class: "btn margtop"%>
      </div>
    <% end %>

app/views/products/edit.html.erb
<div class="container">
  <div class="row">
      <h3>Edita Producto:</h3>
      <%= render 'form' %>
      <%= link_to 'Show', @product %> |
	  <%= link_to 'Back', products_path %>
  </div>
</div>

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="col s12">
       <p id="notice"><%= notice %></p>
       <h2>Lista de Productos</h2>
    </div> 
    <% @products.each do |product| %> 
        <div class="col s3">
          <div class="card small">
            <div class="card-image col s10 offset-s1 ">
              <%= image_tag product.cover.url, class: "responsive-img" %> 
            </div>
            <div class="card-content card-padding col s10">
              <center><h5 class="blue-text text-darken-2"><%= link_to product.nombre, product  %></h5></center> 
              Tamaño: <%= product.tamaño %> <br>  
              <div class="orange-text text-darken-3">
                 <h5>S/. <%= product.pre_venta %><span class="badge new"> <%= product.stock %></span></h5>
              </div> 
              
            </div>
         
          </div>
        </div>   
    <% end %> 
    <div class="col s12">
       <br>
       <%= link_to 'Nuevo Producto', new_product_path %>
    </div>  
  </div>
</div>





     
        
      
    

app/views/products/new.html.erb
<div class="container">
  <div class="row">
      <h3>Nuevo Producto:</h3>
      <%= render 'form' %>
      <%= link_to 'Salir', products_path %>
  </div>
</div>

app/views/products/show.html.erb
<div class="container">
  <div class="row">
    <div class="col s12">
       <p id="notice"><%= notice %></p>
    </div>
    <div class="col s12">
        <h4 class="center-align blue-text text-darken-2"><%= @product.nombre %></h4>
    </div> 

    <div class="col s6">
        <%= image_tag @product.cover.url, height:"430px", width: "460px", class: "center-align" %>
    </div>

    <div class="col s6">
        
       <div class="card-panel grey lighten-5 z-depth-1">
           <strong>Tamaño: </strong> <%= @product.tamaño %>
       </div>

       <div class="card-panel grey lighten-5 z-depth-1 ">
           <strong>Marca: </strong><%= @product.marca %>
       </div>

       <div class="card-panel grey lighten-5 z-depth-1">
           <%= @product.descripcion %>
       </div>

       <div class="card-panel grey lighten-5 z-depth-1">
           <strong>Stock: </strong><%= @product.stock %>
       </div>
       <div class="card-panel grey lighten-5 z-depth-1">
          <div class="orange-text text-darken-3">
              <h4 class="center-align">S/. <%= @product.pre_venta %></h4>
          </div> 
       </div>
    </div>
   

    <div class="col s12">
    <%@product.categories.each do |category| %>
      <div class="btn green darken-4">
        <%= link_to category.nombre, category %>
      </div> 
       <% end -%>
      
    </div>

    <div class="col s12">
       <br><br>
       <%= link_to 'Editar', edit_product_path(@product) %> |
       <%= link_to 'Regresar', products_path %> 
    </div>

  </div>
</div>